version: "3.8"

services:
  email-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - AMQP_URL=amqp://guest:guest@rabbitmq:5672/
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - SMTP_HOST=sandbox.smtp.mailtrap.io
      - SMTP_PORT=587
      - SMTP_USER=f3665b216154ca
      - SMTP_PASS=d449e5735c64be
    depends_on:
      - rabbitmq
    volumes:
      - ./templates:/root/templates
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # AMQP protocol port
      - "15673:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  rabbitmq_data:
